In [5]:
import numpy as np
import pandas as pd

In [6]:
#1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.
arr=np.arange(1,11)
matrix=arr.reshape(2,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
#2. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.
arr1=np.arange(1,21)
result=arr1[5:16]
result

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [8]:
#3. How to compute the mean, median, and standard deviation of a numpy array?Use the array you created above
arr1=np.arange(1,21)
print("Mean:",np.mean(arr1))
print("Median:",np.median(arr1))
print("Standard deviation:",np.std(arr1))


Mean: 10.5
Median: 10.5
Standard deviation: 5.766281297335398


In [9]:
#4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting.
x=np.array([[10,20,30,40],
            [50,60,70,80],
            [90,100,110,120]])
y=np.array([1,2,3,4])
result=x-y
result

array([[  9,  18,  27,  36],
       [ 49,  58,  67,  76],
       [ 89,  98, 107, 116]])

In [22]:
#5. Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data.
data={
        "name": ["Aman", "Bina", "Charlie", "David", "Eva",
             "Farhan", "Grace", "Hari", "Isha", "John"],
    "age": [22, 31, 28, 35, 27, 40, 33, 25, 30, 29],
    "gender": ["Male", "Female", "Male", "Male", "Female",
               "Male", "Female", "Male", "Female", "Male"]
}
df=pd.DataFrame(data)
df

,name,age,gender
0,Aman,22,Male
1,Bina,31,Female
2,Charlie,28,Male
3,David,35,Male
4,Eva,27,Female
5,Farhan,40,Male
6,Grace,33,Female
7,Hari,25,Male
8,Isha,30,Female
9,John,29,Male


In [23]:
#1) Add a new column to the data frame created in question 1, called occupation.The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.
occupations=["Programmer","Manager","Analyst","Programmer","Manager","Analyst","Programmer","Manager","Analyst","Programmer"]
df["occupation"]=occupations
df

,name,age,gender,occupation
0,Aman,22,Male,Programmer
1,Bina,31,Female,Manager
2,Charlie,28,Male,Analyst
3,David,35,Male,Programmer
4,Eva,27,Female,Manager
5,Farhan,40,Male,Analyst
6,Grace,33,Female,Programmer
7,Hari,25,Male,Manager
8,Isha,30,Female,Analyst
9,John,29,Male,Programmer


In [24]:
#2) Select the rows of the dataframe where the age is greater than or equal to 30.
filtered_df = df[df["age"] >= 30]
filtered_df

,name,age,gender,occupation
1,Bina,31,Female,Manager
3,David,35,Male,Programmer
5,Farhan,40,Male,Analyst
6,Grace,33,Female,Programmer
8,Isha,30,Female,Analyst


In [26]:
#3) Convert this dataframe to a CSV file and read that CSV file, and finally display the contents.
df.to_csv("students.csv", index=False)

new_df = pd.read_csv("students.csv")

new_df

,name,age,gender,occupation
0,Aman,22,Male,Programmer
1,Bina,31,Female,Manager
2,Charlie,28,Male,Analyst
3,David,35,Male,Programmer
4,Eva,27,Female,Manager
5,Farhan,40,Male,Analyst
6,Grace,33,Female,Programmer
7,Hari,25,Male,Manager
8,Isha,30,Female,Analyst
9,John,29,Male,Programmer
